### ISSUE TITLE
Posting link in full screen mode scrolls to top of document

### ISSUE THREAD

**Issue by gagandeepgill** [Canner/canner-slate-editor-archive#28]
Not sure if it was intended or not. But adding a link in full-screen mode will scroll you all the way to the top of the document. This could be annoying for users if they are trying to edit and post a link somewhere that is not near the top in a large document.

But overall this is a very nice editor! Keep up the good work! 👍

**Comment by chilijung** [comment]
@gagandeepgill this is fixed in latest version https://github.com/Canner/canner-slate-editor and this repo is moved here! thanks!
