### ISSUE TITLE
BundlePhobia reports a MissingDependencyError

### ISSUE THREAD

**Issue by Gabriel-Macena** [Canner/canner-slate-editor-archive#32]
When searching for canner-slate-editor package on BundlePhobia, it reports a MissingDependencyError.

Error message: "This package (or this version) uses `antd`, `immutable` and `slate-schema-violations`, but does not specify them either as a dependency or a peer dependency".

**Comment by chilijung** [comment]
@Gabriel-Macena this is fixed in latest version https://github.com/Canner/canner-slate-editor and this repo is moved here! thanks!
